<?php

namespace TravelBundle\Repository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByHotelWithRoom($nbRoom, $city = '', $star = 1)
    {
        return $this->createQueryBuilder('h')
            ->select('h, COUNT(r.hotel) as nbroom')
            ->join('TravelBundle:Room', 'r')
            ->groupBy('r.hotel, h.id')
                ->having('nbroom>=:nbroom')
                    ->setParameter('nbroom', $nbRoom)
            ->where('r.book >= :book')
                ->setParameter('book', 0)
            ->andWhere('h.stars >= :stars')
                ->setParameter('stars', $star)
             ->andWhere('h.city=:city')
                ->setParameter('city', $city)
        ->getQuery()->getResult();
    }

    public function findByStarsAndCity($city, $star = 1)
    {
        return $this->createQueryBuilder('h')
            ->where('h.stars >= :stars')
                ->setParameter('stars', $star)
             ->andWhere('h.city=:city')
                ->setParameter('city', $city)
        ->getQuery()->getResult();
    }

}
