<?php

namespace HotelBundle\Repository;

/**
 * RequetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequetteRepository extends \Doctrine\ORM\EntityRepository
{
}
